"""Compute the per-world WAD->physical altitude scale and write it to
``zwift_routes/world_altitude_scale.json``.

Zwift's WAD route geometry (``zwift_routes/world_*.json`` ``alt`` arrays) stores
vertical altitude in a world-specific unit that is not always physical metres:
Watopia/Paris/Scotland/Yorkshire(13) read ~2x true metres, New York ~1.32x, and
most other worlds are already physical. Horizontal distance is always physical.

The factor for a world is the median of ``published_ascent / raw_WAD_gross_ascent``
across all of that world's routes (published ascent comes from Zwift's own route
metadata in ``index.json``). The median is robust to long composite routes whose
gross ascent is inflated by geometry noise. Values within 0.05 of 0.5 or 1.0 are
snapped to those clean constants; anything else (e.g. New York) is kept as the
empirical median.

Run:  python tools/compute_world_altitude_scale.py
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROUTES_DIR = ROOT / "zwift_routes"
INDEX_PATH = ROUTES_DIR / "index.json"
OUTPUT_PATH = ROUTES_DIR / "world_altitude_scale.json"

# Friendly names for context only (keyed by mapID).
WORLD_NAMES = {
    1: "Watopia", 2: "Richmond", 3: "London", 4: "New York", 5: "Innsbruck",
    6: "Bologna", 7: "Yorkshire", 8: "Crit City", 9: "Makuri Islands",
    10: "France", 11: "Paris", 12: "Scotland", 13: "World 13",
}

SNAP_TARGETS = (0.5, 1.0)
SNAP_TOLERANCE = 0.05


def gross_ascent(alt: list[float]) -> float:
    return sum(max(0.0, alt[i + 1] - alt[i]) for i in range(len(alt) - 1))


def median(values: list[float]) -> float:
    s = sorted(values)
    n = len(s)
    if n == 0:
        return float("nan")
    mid = n // 2
    return s[mid] if n % 2 else 0.5 * (s[mid - 1] + s[mid])


def snap(value: float) -> float:
    for target in SNAP_TARGETS:
        if abs(value - target) <= SNAP_TOLERANCE:
            return target
    return round(value, 3)


def main() -> None:
    index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))

    # Cache world files so each is read once.
    world_cache: dict[str, dict] = {}
    ratios: dict[int, list[float]] = defaultdict(list)

    for entry in index:
        map_id = entry.get("mapID")
        published = float(entry.get("ascent_m") or 0.0)
        if map_id is None or published <= 0:
            continue
        file_name = entry.get("file")
        if not file_name:
            continue
        world = world_cache.get(file_name)
        if world is None:
            world = json.loads((ROUTES_DIR / file_name).read_text(encoding="utf-8"))
            world_cache[file_name] = world
        route = next(
            (r for r in world.get("routes", [])
             if r.get("nameHash") == entry.get("nameHash")),
            None,
        )
        if route is None:
            continue
        alt = (route.get("route") or {}).get("alt") or []
        if len(alt) < 3:
            continue
        raw = gross_ascent(alt)
        if raw <= 0:
            continue
        ratios[map_id].append(published / raw)

    worlds: dict[str, dict] = {}
    for map_id in sorted(ratios):
        vals = ratios[map_id]
        med = median(vals)
        worlds[str(map_id)] = {
            "world": WORLD_NAMES.get(map_id, f"World {map_id}"),
            "scale": snap(med),
            "n_routes": len(vals),
            "median_raw": round(med, 4),
            "min_raw": round(min(vals), 4),
            "max_raw": round(max(vals), 4),
        }

    output = {
        "description": (
            "Per-world WAD->physical altitude scale. Multiply raw WAD route "
            "altitude (zwift_routes/world_*.json 'alt') by 'scale' to get "
            "physical metres. Default 1.0 for any world not listed. Generated by "
            "tools/compute_world_altitude_scale.py."
        ),
        "default_scale": 1.0,
        "worlds": worlds,
    }
    OUTPUT_PATH.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    print(f"{'world':>3}  {'name':<16} {'n':>4}  {'scale':>6}  "
          f"{'median':>7}  {'min':>6}  {'max':>6}")
    for map_id in sorted(ratios):
        w = worlds[str(map_id)]
        print(f"{map_id:>3}  {w['world']:<16} {w['n_routes']:>4}  "
              f"{w['scale']:>6}  {w['median_raw']:>7}  "
              f"{w['min_raw']:>6}  {w['max_raw']:>6}")


if __name__ == "__main__":
    main()
