name: Deploy Azure Function

on:
  push:
    branches: [main]
    paths:
      - "azure_function/**"
  workflow_dispatch: # Allow manual triggers

env:
  AZURE_FUNCTIONAPP_NAME: zwiftgames-func-hc4trbmw4t6kc
  PYTHON_VERSION: "3.12"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: azure_function

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
